"""Keep the homepage focused: link to the canonical daily five-pick page.

The detailed daily selection is generated by build_daily_deals.py at /today/.
This script intentionally does not calculate a separate homepage top 3, so the
homepage and /today/ can never disagree about which products are today's picks.
"""
from pathlib import Path
import re

PAGE = Path("site/index.html")

if not PAGE.exists():
    raise SystemExit("site/index.html not found")

markup = PAGE.read_text(encoding="utf-8")

# Remove a legacy three-pick block if an earlier generated index contains one.
markup = re.sub(
    r'<section class="daily-buy-picks" id="daily-buy-picks".*?</section>\s*<script>.*?daily_pick_click.*?</script>\s*',
    '',
    markup,
    flags=re.DOTALL,
)

# Remove the legacy styling as well when rebuilding from an already generated page.
markup = re.sub(
    r'\.daily-buy-picks\{.*?@media\(min-width:760px\)\{\.daily-pick-grid\{grid-template-columns:repeat\(3,1fr\)\}\}\s*',
    '',
    markup,
    flags=re.DOTALL,
)

# build_daily_deals.py injects the canonical /today/ entry later in the workflow.
# Do not add another competing daily-products block here.
PAGE.write_text(markup, encoding="utf-8")
print("Homepage daily top-3 disabled; canonical daily picks live at /today/")
